# theme: jekyll-theme-cayman
title: Simulation-based Inference
description: Simulation-based Inference is the next evolution in statistics

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" 
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: home
      toc: true
      author_profile: false


  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
exclude: 
  - scholar/
  - main.py
  - tmp.ipynb
  - CNAME