name: Weekly pull

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every week on sunday 0:00

  workflow_dispatch:  # Add manually dispatch option

jobs:
  my_cron_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt

    - name: Pull new articles
      env:
        SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python main.py --crawl

    - name: check for changed files
      run: |
        changed_files=$(git status --porcelain)
        if [ -n "$changed_files" ]; then
          echo "changed=true" >> $GITHUB_ENV
          echo "=== change detected ==="
          echo "$changed_files"
        else
          echo "changed=false" >> $GITHUB_ENV
          echo "=== no change detected ==="
        fi
    - if: ${{ env.changed == 'true' }}
      name: Commit changes
      run: |
        git config --local user.email "github-action[bot]@github.com"
        git config --local user.name "GitHub Action Bot"
        git add -A
        git commit -m "auto update publications"

    - if: ${{ env.changed == 'true' }}
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
